//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNameSpace
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Schedule
    {
        public int id { get; set; }
        public string BLOCK { get; set; }
        public string Panel { get; set; }
        public string Pqty { get; set; }
        public string Cqty { get; set; }
        public string Sqty { get; set; }
        public string DESCRIPTION { get; set; }
        public string LENGTH { get; set; }
        public string WIDTH { get; set; }
        public string MSSREFNO { get; set; }
        public string BATCH { get; set; }
        public string NOTEREMARKS { get; set; }
        public Nullable<System.DateTime> StartDATE { get; set; }
        public Nullable<System.DateTime> completedDATE { get; set; }
        public string MSSWeight { get; set; }
        public string PANELWeight { get; set; }
        public string DoneBy { get; set; }
        public string SDP { get; set; }
        public string Checker { get; set; }
        public string SCP { get; set; }
        public string KDP { get; set; }
        public string KCP { get; set; }
        public string KPIA { get; set; }
        public string KPIB { get; set; }
        public string KPIN { get; set; }
        public string KPI { get; set; }
        public string KPIM { get; set; }
        public string DCKPI { get; set; }
        public string CCKPI { get; set; }
        public string CKPIM { get; set; }
        public string Recheck { get; set; }
        public string Remark { get; set; }
        public Nullable<double> PSDM { get; set; }
        public Nullable<double> PSCM { get; set; }
        public Nullable<double> PKDM { get; set; }
        public Nullable<double> PKCM { get; set; }
        public Nullable<double> ASDM { get; set; }
        public Nullable<double> ASCM { get; set; }
        public Nullable<double> AKDM { get; set; }
        public Nullable<double> AKCM { get; set; }
        public string Project { get; set; }
        //
       
    }
}
